# Generated by Django 5.1.1 on 2024-09-17 21:33

import libabook.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='text',
            field=models.FileField(blank=True, storage=libabook.storages.PrivateMediaStorage(), upload_to=''),
        ),
    ]
